# Generated by Django 4.1 on 2022-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
