from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('product/',views.product,name='product'),
    path('computer/',views.computer,name='computer'),
    path('laptop/',views.laptop,name='laptop'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('change_password/',views.change_password,name='change_password'),
    path('logout/',views.logout, name='logout'),
    path('forgot_password/',views.forgot_password,name='forgot_password'),
    path('otp/',views.otp,name='otp'),
    path('new_password/',views.new_password,name='new_password'),
    path('profile_pic/',views.profile_pic,name='profile_pic'),
    path('seller_change_password/',views.seller_change_password,name='seller_change_password'),
    path('seller_add_product/', views.seller_add_product, name='seller_add_product'),
    path('seller_view_product/', views.seller_view_product, name='seller_view_product'),
    path('seller_index/',views.seller_index, name='seller_index'),
    path('seller_product_details/<int:pk>/',views.seller_product_details,name='seller_product_details'),
    path('seller_edit_product/<int:pk>/',views.seller_edit_product,name='seller_edit_product'),
    path('seller_delet_product/<int:pk>/',views.seller_delet_product,name='seller_delet_product'),
    path('product_by_category/<str:pc>/',views.product_by_category,name='product_by_category'),
    path('product_details/<int:pk>/',views.product_details,name='product_details'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('change_qty/<int:pk>/',views.change_qty,name='change_qty'),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('my_order/',views.my_order,name='my_order'),
    path('ajax/validate_email/',views.validate_email,name='validate_email'),
    path('contact/',views.contact,name='contact'),
    path('subscribe/',views.subscribe,name='subscribe'),
]
    